# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10bbf1628c285dfe4ce2e9efce198a90cd9825d4733a21b649056d72b435b6e818439cdf2b53960145e213066f4580486db64bb46771771367f2e8f5119a9e96

test:
  secret_key_base: e1c6152c0a3a0948c26b902733e6fc45bf1213ce5d070345e01d6e3eac3a2db90cba370eedbaa24d403d602bc1525d5b2eff8d668a4a2b813121e140151a314f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
